//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange,Radius_1,Radius_2
        ///IPE 100,100,55,4.1,5.7,,
        ///IPE 120,120,64,4.4,6.3,,
        ///IPE 140,140,73,4.7,6.9,,
        ///IPE 160,160,82,5,7.4,,
        ///IPE 180,180,91,5.3,8,,
        ///IPE 200,200,100,5.6,8.5,,
        ///IPE 220,220,110,5.9,9.2,,
        ///IPE 240,240,120,6.2,9.8,,
        ///IPE 270,270,135,6.6,10.2,,
        ///IPE 300,300,150,7.1,10.7,,
        ///IPE 330,330,160,7.5,11.5,,
        ///IPE 360,360,170,8,12.7,,
        ///IPE 400,400,180,8.6,13.5,,
        ///IPE 450,450,190,9.4,14.6,,
        ///IPE 500,500,200,10.2,16,,
        ///IPE 550,550,210,11.1,17.2,,
        ///IPE 600,600,220,12,19,,
        ///IPE 750 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog {
            get {
                return ResourceManager.GetString("steel_profile_calatog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Depth,Width,Web,Flange,Radius
        ///HEA100,96,100,5,8,12
        ///HEA120,114,120,5,8,12
        ///HEA140,133,140,5.5,8.5,12
        ///HEA160,152,160,6,9,15
        ///HEA180,171,180,6,9.5,15
        ///HEA200,190,200,6.5,10,18
        ///HEA220,210,220,7,11,18
        ///HEA240,230,240,7.5,12,21
        ///HEA260,250,260,7.5,12.5,24
        ///HEA280,270,280,8,13,24
        ///HEA300,290,300,8.5,14,27
        ///HEA320,310,300,9,15.5,27
        ///HEA340,330,300,9.5,16.5,27
        ///HEA360,350,300,10,17.5,27
        ///HEA400,390,300,11,19,27
        ///HEA450,440,300,11.5,21,27
        ///HEA500,490,300,12,23,27
        ///HEA550,540,300,12.5,24,27
        ///HEA600,590,300 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_HEA {
            get {
                return ResourceManager.GetString("steel_profile_calatog_HEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Depth,Width,Web,Flange,Radius
        ///HE 100 AA,91,100,4.2,5.5,12
        ///HE 120 AA,109,120,4.2,5.5,12
        ///HE 140 AA,128,140,4.3,6,12
        ///HE 60 AA,148,160,4.5,7,15
        ///HE 180 AA,167,180,5,7.5,15
        ///HE 200 AA,186,200,5.5,8,18
        ///HE 220 AA,205,220,6,8.5,18
        ///HE 240 AA,224,240,6.5,9,21
        ///HE 260 AA,244,260,6.5,9.5,24
        ///HE 280 AA,264,280,7,10,24
        ///HE 300 AA,283,300,7.5,10.5,27
        ///HE 320 AA,301,300,8,11,27
        ///HE 340 AA,320,300,8.5,11.5,27
        ///HE 360 AA,339,300,9,12,27
        ///HE 400 AA,378,300,9.5,13,27
        ///HE 450 AA,425,300,10,13.5,27
        ///HE 500 AA,472,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_HEAA {
            get {
                return ResourceManager.GetString("steel_profile_calatog_HEAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Depth,Width,Web,Flange,Radius
        ///HEB100,100,100,6,10,12
        ///HEB120,120,120,6.5,11,12
        ///HEB140,140,140,7,12,12
        ///HEB160,160,160,8,13,15
        ///HEB180,180,180,8.5,14,15
        ///HEB200,200,200,9,15,18
        ///HEB220,220,220,9.5,16,18
        ///HEB240,240,240,10,17,21
        ///HEB260,260,260,10,17.5,24
        ///HEB280,280,280,10.5,18,24
        ///HEB300,300,300,11,19,27
        ///HEB320,320,300,11.5,20.5,27
        ///HEB340,340,300,12,21.5,27
        ///HEB360,360,300,12.5,22.5,27
        ///HEB400,400,300,13.5,24,27
        ///HEB450,450,300,14,26,27
        ///HEB500,500,300,14.5,28,27
        ///HEB550,550,300,15,29,27
        ///HEB600 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_HEB {
            get {
                return ResourceManager.GetString("steel_profile_calatog_HEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Depth,Width,Web,Flange,Radius
        ///HEM100,120,106,12,20,12
        ///HEM120,140,126,12.5,21,12
        ///HEM140,160,146,13,22,12
        ///HEM160,180,166,14,23,15
        ///HEM180,200,186,14.5,24,15
        ///HEM200,220,206,15,25,18
        ///HEM220,240,226,15.5,26,18
        ///HEM240,270,248,18,32,21
        ///HEM260,290,268,18,32.5,24
        ///HEM280,310,288,18.5,33,24
        ///HEM300,340,310,21,39,27
        ///HEM320,359,309,21,40,27
        ///HEM340,377,309,21,40,27
        ///HEM360,395,308,21,40,27
        ///HEM400,432,307,21,40,27
        ///HEM450,478,307,21,40,27
        ///HEM500,524,306,21,40,27
        ///HEM550,572,306,21,40,27
        ///HEM600,620,30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_HEM {
            get {
                return ResourceManager.GetString("steel_profile_calatog_HEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange
        ///IPE 100,100,55,4.1,5.7
        ///IPE 120,120,64,4.4,6.3
        ///IPE 140,140,73,4.7,6.9
        ///IPE 160,160,82,5,7.4
        ///IPE 180,180,91,5.3,8
        ///IPE 200,200,100,5.6,8.5
        ///IPE 220,220,110,5.9,9.2
        ///IPE 240,240,120,6.2,9.8
        ///IPE 270,270,135,6.6,10.2
        ///IPE 300,300,150,7.1,10.7
        ///IPE 330,330,160,7.5,11.5
        ///IPE 360,360,170,8,12.7
        ///IPE 400,400,180,8.6,13.5
        ///IPE 450,450,190,9.4,14.6
        ///IPE 500,500,200,10.2,16
        ///IPE 550,550,210,11.1,17.2
        ///IPE 600,600,220,12,19
        ///IPE 750 x 134,750,264,12,15.5
        ///IPE 750 x 147,753,265,13.2,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_IPE {
            get {
                return ResourceManager.GetString("steel_profile_calatog_IPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange,Radius_1,Radius_2
        ///IPN 80,80,42,3.9,5.9,3.9,2.3
        ///IPN 80,80,42,3.9,5.9,2,&lt;1
        ///IPN 100,100,50,4.5,6.8,4.5,2.7
        ///IPN 100,100,50,4.5,6.8,2,&lt;1
        ///IPN 120,120,58,5.1,7.7,5.1,3.1
        ///IPN 120,120,58,5.1,7.7,2,&lt;1
        ///IPN 140,140,66,5.7,8.6,5.7,3.4
        ///IPN 140,140,66,5.7,8.6,2,&lt;1
        ///IPN 160,160,74,6.3,9.5,6.3,3.8
        ///IPN 160,160,74,6.3,9.5,2,&lt;1
        ///IPN 180,180,82,6.9,10.4,6.9,4.1
        ///IPN 180,180,82,6.9,10.4,2,&lt;1
        ///IPN 200,200,90,7.5,11.3,7.5,4.5
        ///IPN 200,200,90,7.5,11.3,2,&lt;1
        ///IPN 220,220,98,8.1,12.2,2,&lt;1
        ///IPN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_IPN {
            get {
                return ResourceManager.GetString("steel_profile_calatog_IPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Web,Radius
        ///L 15x15x2,0.45,15,2
        ///L 15x15x3,0.66,15,3
        ///L 20x20x2,0.89,20,2
        ///L 20x20x3,0.9,20,3
        ///L 20x20x4,1.16,20,4
        ///L 25x25x3,1.14,25,3
        ///L 25x25x4,1.48,25,4
        ///L 25x25x5,1.82,25,5
        ///L 30x30x3,1.39,30,3
        ///L 30x30x4,1.81,30,4
        ///L 30x30x5,2.22,30,5
        ///L 30x30x6,2.61,30,6
        ///L 35x35x4,2.13,35,4
        ///L 35x35x5,2.62,35,5
        ///L 40x40x3,1.87,40,3
        ///L 40x40x4,2.46,40,4
        ///L 40x40x5,3.03,40,5
        ///L 40x40x6,3.58,40,6
        ///L 45x45x3,2.13,45,3
        ///L 45x45x4,2.79,45,4
        ///L 45x45x5,3.44,45,5
        ///L 50x50x3,2.37,50,3
        ///L 50x50x4,3.11,50,4
        ///L 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_L_equal {
            get {
                return ResourceManager.GetString("steel_profile_calatog_L_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Radius
        ///L 20x10x3,20,10,3,3.5
        ///L 25x15x3,25,15,3,3.5
        ///L 30x15x3,30,15,3,5
        ///L 30x20x3,30,20,3,5
        ///L 30x20x4,30,20,4,5
        ///L 40x20x3,40,20,3,5
        ///L 40x20x4,40,20,4,6
        ///L 40x20x5,40,20,5,6
        ///L 40x30x3,40,30,3,5
        ///L 40x30x4,40,30,4,6
        ///L 40x30x5,40,30,5,6
        ///L 45x30x3,45,30,3,7
        ///L 45x30x4,45,30,4,7
        ///L 45x30x5,45,30,5,7
        ///L 50x30x3,50,30,3,7
        ///L 50x30x4,50,30,4,7
        ///L 50x30x5,50,30,5,7
        ///L 50x40x3,50,40,3,7
        ///L 50x40x4,50,40,4,7
        ///L 50x40x5,50,40,5,7
        ///L 60x30x5,60,30,5,8
        ///L 60x30x6,60,30,6,8
        ///L 60x30x7,60, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_L_unequal {
            get {
                return ResourceManager.GetString("steel_profile_calatog_L_unequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web
        ///T 20x20x3,20,20,3
        ///T 20x20x4,20,20,4
        ///T 25x25x3,25,25,3
        ///T 25x25x3.5,25,25,3.5
        ///T 25x25x4,25,25,4
        ///T 30x30x3,30,30,3
        ///T 30x30x4,30,30,4
        ///T 30x30x5,30,30,5
        ///T 35x35x3,35,35,3
        ///T 35x35x4,35,35,4
        ///T 35x35x5,35,35,5
        ///T 40x40x3,40,40,3
        ///T 40x40x4,40,40,4
        ///T 40x40x5,40,40,5
        ///T 40x40x6,40,40,6
        ///T 45x45x3,45,45,3
        ///T 45x45x4,45,45,4
        ///T 45x45x5,45,45,5
        ///T 45x45x6,45,45,6
        ///T 50x50x3,50,50,3
        ///T 50x50x4,50,50,4
        ///T 50x50x5,50,50,5
        ///T 50x50x6,50,50,6
        ///T 50x50x7,50,50,7
        ///T 50x50x8,50,50,8
        ///T 60x60 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_T {
            get {
                return ResourceManager.GetString("steel_profile_calatog_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web
        ///TB 20,20,40,4
        ///TB 25,25,50,5
        ///TB 30,30,60,5.5
        ///TB 35,35,70,6
        ///TB 40,40,80,7
        ///TB 50,50,100,8.5
        ///TB 60,60,120,10.
        /// </summary>
        internal static string steel_profile_calatog_TB {
            get {
                return ResourceManager.GetString("steel_profile_calatog_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange
        ///UPA 50x25x3,50,25,3,3
        ///UPA 60x30x5,60,30,5,5
        ///UPA 80x40x4,80,40,4,4
        ///UPA 80x40x5,80,40,5,5
        ///UPA 80x40x6,80,40,6,6
        ///UPA 100x50x4,100,50,4,4
        ///UPA 100x50x5,100,50,5,5
        ///UPA 100x50x6,100,50,6,6
        ///UPA 120x60x5,120,60,5,5
        ///UPA 120x60x6,120,60,6,6
        ///UPA 130x65x6,130,65,6,6
        ///UPA 130x65x9,130,65,9,9
        ///UPA 140x70x7,140,70,7,7
        ///UPA 150x75x6,150,75,6,6
        ///UPA 150x75x9,150,75,9,9
        ///UPA 160x80x6,160,80,6,6
        ///UPA 160x80x8,160,80,8,8
        ///UPA 180x90x8,180,90,8,8
        ///UPA 200x100x8,200,100,8,8
        ///UPA 200x100x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_UPA {
            get {
                return ResourceManager.GetString("steel_profile_calatog_UPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange
        ///UPE 80,80,50,4,7
        ///UPE 100,100,55,4.5,7.5
        ///UPE 120,120,60,5,8
        ///UPE 140,140,65,5,9
        ///UPE 160,160,70,5.5,9.5
        ///UPE 180,180,75,5.5,10.5
        ///UPE 200,200,80,6,11
        ///UPE 220,220,85,6.5,12
        ///UPE 240,240,90,7,12.5
        ///UPE 270,270,95,7.5,13.5
        ///UPE 300,300,100,9.5,15
        ///UPE 330,330,105,11,16
        ///UPE 360,360,110,12,17
        ///UPE 400,400,115,13.5,18.
        /// </summary>
        internal static string steel_profile_calatog_UPE {
            get {
                return ResourceManager.GetString("steel_profile_calatog_UPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange,Radius_1,Radius_2
        ///UPN 20x10x3,20,10,3,3.5,3.5,2.5
        ///UPN 30x15x4,30,15,4,4.5,4.5,2.5
        ///UPN 30x15x4,30,15,4,4.5,1,&lt;1
        ///UPN 30x33x5,30,33,5,7,7,3
        ///UPN 40x20x3,40,20,3,3.3,3.3,3
        ///UPN 40x20x3,40,20,3,3.5,1,&lt;1
        ///UPN 40x20x4,40,20,4,4.5,4.5,3
        ///UPN 40x20x4,40,20,4,4.5,1,&lt;1
        ///UPN 40x35x5,40,35,5,7,7,3
        ///UPN 40x35x5,40,35,5,7,1,&lt;1
        ///UPN 50x25x5,50,25,5,6,5,3.5
        ///UPN 50x25x5,50,25,5,6,1,&lt;1
        ///UPN 50,50,38,5,7,7,3.5
        ///UPN 50,50,38,5,7,1,&lt;1
        ///UPN 60x30x6,60,30,6,6,6,3
        ///UPN 60x30x6,60,30,6,6,1,&lt;1
        ///UP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog_UPN {
            get {
                return ResourceManager.GetString("steel_profile_calatog_UPN", resourceCulture);
            }
        }
    }
}
