//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile,Height,Width,Web,Flange,Radius_1,Radius_2
        ///IPE 100,100,55,4.1,5.7,,
        ///IPE 120,120,64,4.4,6.3,,
        ///IPE 140,140,73,4.7,6.9,,
        ///IPE 160,160,82,5,7.4,,
        ///IPE 180,180,91,5.3,8,,
        ///IPE 200,200,100,5.6,8.5,,
        ///IPE 220,220,110,5.9,9.2,,
        ///IPE 240,240,120,6.2,9.8,,
        ///IPE 270,270,135,6.6,10.2,,
        ///IPE 300,300,150,7.1,10.7,,
        ///IPE 330,330,160,7.5,11.5,,
        ///IPE 360,360,170,8,12.7,,
        ///IPE 400,400,180,8.6,13.5,,
        ///IPE 450,450,190,9.4,14.6,,
        ///IPE 500,500,200,10.2,16,,
        ///IPE 550,550,210,11.1,17.2,,
        ///IPE 600,600,220,12,19,,
        ///IPE 750 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string steel_profile_calatog {
            get {
                return ResourceManager.GetString("steel_profile_calatog", resourceCulture);
            }
        }
    }
}
